import React from 'react';
import Image from 'next/image';

const galleryImages = [
  {
    src: '/images/nature.png',
    alt: 'AI Generated Nature Scene',
    title: 'Nature',
    description: 'Beautiful landscapes and natural scenes generated by AI'
  },
  {
    src: '/images/fantasy.png',
    alt: 'AI Generated Fantasy Character',
    title: 'Fantasy',
    description: 'Magical and fantastical scenes created by AI'
  },
  {
    src: '/images/landscape.png',
    alt: 'AI Generated Landscape',
    title: 'Landscape',
    description: 'Stunning landscapes crafted by artificial intelligence'
  },
  {
    src: '/images/portrait.png',
    alt: 'AI Generated Portrait',
    title: 'Portrait',
    description: 'Unique portraits generated using AI'
  }
];

const Gallery = () => {
  return (
    <section id="gallery" className="py-16 px-4 bg-gray-900">
      <div className="max-w-6xl mx-auto">
        <h2 className="text-3xl font-bold text-center mb-12 bg-gradient-to-r from-purple-400 to-pink-600 text-transparent bg-clip-text">
          Genova AI Gallery
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8">
          {galleryImages.map((image, index) => (
            <div key={index} className="relative group">
              <div className="aspect-w-16 aspect-h-9 rounded-xl overflow-hidden bg-gray-800">
                <Image
                  src={image.src}
                  alt={image.alt}
                  width={800}
                  height={450}
                  className="object-cover transform transition-transform duration-300 group-hover:scale-105"
                />
                <div className="absolute inset-0 bg-black bg-opacity-40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-6">
                  <h3 className="text-xl font-semibold text-white mb-2">{image.title}</h3>
                  <p className="text-gray-200 text-sm">{image.description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Gallery;
